import type { NextPage } from 'next'
import Head from 'next/head'
import Banner from "../components/Banner";
import Header from "../components/Header";
import SmallCard from "../components/SmallCard";

interface ExploreData{
	img:string;
	distance:string;
	location:string;
}
const Home: NextPage<any> = (props:{exploreData:ExploreData[]}) => {
	const {exploreData} = props;
  return (
    <div className="">
      <Head>
        <title>Timoy Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Header/>
			<Banner/>
			<main className="max-w-7xl mx-auto px-8 sm:px-16">
				<section className="pt-6">
					<h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
					{/* Pull some data from a server - API endpoints */}
					<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
						{exploreData?.map((item) => (
							<SmallCard 
								key={item.img} 
								img={item.img} 
								location={item.location} 
								distance={item.distance} 
							/>
						))}
					</div>
				</section>
				<section>
					<h2 className="text-4xl font-semibold py-4">Live Anywhere</h2>
				</section>
			</main>
    </div>
  )
}

export const getStaticProps = async () => {
	const exploreData = await fetch("https://links.papareact.com/pyp");
	const res = await exploreData.json();
	
	const cardsData = await fetch("https://")
	return {
		props:{
			exploreData:res,
		}
	}
}
export default Home
